# Generated by Django 4.1.2 on 2022-10-20 18:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('community_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Community ID')),
                ('community_name', models.CharField(max_length=255, verbose_name='Community Name')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ユーザID')),
                ('password', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(default='', max_length=255)),
                ('user_name', models.CharField(max_length=255, verbose_name='ユーザ名')),
                ('address', models.CharField(max_length=255, verbose_name='住所')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
        ),
        migrations.CreateModel(
            name='CommunityMembers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('community_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_communities', to='rest_api.community')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_communities', to='rest_api.user')),
            ],
        ),
        migrations.AddField(
            model_name='community',
            name='users',
            field=models.ManyToManyField(through='rest_api.CommunityMembers', to='rest_api.user'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False, verbose_name='記事のID')),
                ('uri', models.URLField(max_length=300, null=True, verbose_name='URI')),
                ('article_name', models.CharField(max_length=255, verbose_name='投稿タイトル')),
                ('article_content', models.TextField(max_length=255, verbose_name='投稿内容')),
                ('meeting_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='開催日時')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='投稿作成日時')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='rest_api.user', verbose_name='記事を投稿するユーザID')),
            ],
        ),
    ]
