# Generated by Django 4.1.2 on 2022-10-14 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ユーザID')),
                ('user_name', models.CharField(max_length=255, verbose_name='ユーザ名')),
                ('address', models.CharField(max_length=255, verbose_name='住所')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
        ),
    ]
