# Generated by Django 4.1.2 on 2022-10-20 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityArticlesOnly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.article')),
                ('community_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.community')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='communities',
            field=models.ManyToManyField(through='rest_api.CommunityArticlesOnly', to='rest_api.community'),
        ),
    ]
