# Generated by Django 4.1.2 on 2022-10-14 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_community'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Member ID')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.community')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.user')),
            ],
        ),
    ]
