# Generated by Django 4.1.2 on 2022-10-20 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_communityarticlesonly_article_communities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityarticlesonly',
            name='article_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles_communities', to='rest_api.article'),
        ),
        migrations.AlterField(
            model_name='communityarticlesonly',
            name='community_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles_communities', to='rest_api.community'),
        ),
    ]
