# Generated by Django 4.1.2 on 2022-10-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_alter_communityarticlesonly_article_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitymembers',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
