# Generated by Django 4.1.2 on 2022-10-14 15:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.CharField(max_length=255, verbose_name='投稿タイトル')),
                ('article_content', models.TextField(max_length=255, verbose_name='投稿内容')),
                ('meeting_time', models.DateTimeField(default=datetime.datetime(2022, 10, 14, 15, 52, 33, 914541, tzinfo=datetime.timezone.utc), verbose_name='開催日時')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 10, 14, 15, 52, 33, 914683, tzinfo=datetime.timezone.utc), verbose_name='投稿作成日時')),
            ],
        ),
        migrations.RenameModel(
            old_name='Member',
            new_name='User_Community',
        ),
        migrations.CreateModel(
            name='Article_Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.article')),
                ('community_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.community')),
            ],
        ),
    ]
