# Generated by Django 4.1.2 on 2022-10-15 00:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_article_rename_member_user_community_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='uri',
            field=models.URLField(max_length=300, null=True, verbose_name='URI'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 15, 0, 57, 41, 827994, tzinfo=datetime.timezone.utc), verbose_name='投稿作成日時'),
        ),
        migrations.AlterField(
            model_name='article',
            name='meeting_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 15, 0, 57, 41, 827877, tzinfo=datetime.timezone.utc), verbose_name='開催日時'),
        ),
    ]
