# Generated by Django 4.1.2 on 2022-10-15 01:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0005_article_uri_alter_article_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 15, 1, 7, 39, 786606, tzinfo=datetime.timezone.utc), verbose_name='投稿作成日時'),
        ),
        migrations.AlterField(
            model_name='article',
            name='meeting_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 15, 1, 7, 39, 786478, tzinfo=datetime.timezone.utc), verbose_name='開催日時'),
        ),
    ]
