# Generated by Django 4.1.2 on 2022-10-15 02:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0006_alter_article_created_at_alter_article_meeting_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 15, 2, 22, 17, 108225, tzinfo=datetime.timezone.utc), verbose_name='投稿作成日時'),
        ),
        migrations.AlterField(
            model_name='article',
            name='meeting_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 15, 2, 22, 17, 108100, tzinfo=datetime.timezone.utc), verbose_name='開催日時'),
        ),
    ]
