# Generated by Django 4.1.2 on 2022-10-18 03:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0007_user_password_alter_article_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 18, 3, 46, 2, 112067, tzinfo=datetime.timezone.utc), verbose_name='投稿作成日時'),
        ),
        migrations.AlterField(
            model_name='article',
            name='meeting_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 18, 3, 46, 2, 111932, tzinfo=datetime.timezone.utc), verbose_name='開催日時'),
        ),
    ]
