# Generated by Django 4.1.2 on 2022-10-18 03:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0008_user_email_alter_article_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='投稿作成日時'),
        ),
        migrations.AlterField(
            model_name='article',
            name='meeting_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='開催日時'),
        ),
    ]
