# Generated by Django 4.1.2 on 2022-10-18 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0009_alter_article_created_at_alter_article_meeting_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityMembers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('community_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_communities', to='rest_api.community')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_communities', to='rest_api.user')),
            ],
        ),
        migrations.AddField(
            model_name='community',
            name='users',
            field=models.ManyToManyField(through='rest_api.CommunityMembers', to='rest_api.user'),
        ),
    ]
