# Generated by Django 4.1.2 on 2022-10-18 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0010_communitymembers_community_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Community',
        ),
    ]
