version: '3.7'

services:
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/backend/
    ports:
      - 8000:8000
    environment:
      - DATABASE_ENGINE=django.db.backends.postgresql
      - DATABASE_DB=sokuseki_db
      - DATABASE_USER=pos_db_user
      - DATABASE_PASSWORD=password1234
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      # setting.pyに記載されているSECRET_KEYを記入
      - SECRET_KEY=hoge
    depends_on:
      - db

  db:
    image: postgres:11.4-alpine
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=pos_db_user
      - POSTGRES_PASSWORD=password1234
      - POSTGRES_DB=sokuseki_db

volumes:
  postgres_db:
