version: '3.7'

services:
  backend:
    build: ./backend
    command: /bin/bash -c "python manage.py runserver 0.0.0.0:8000"
    # データを永続化させる場合の設定。`host:container`でパスを記載
    volumes:
      - ./backend/:/usr/src/backend/
    ports:
      - 8000:8000
    environment:
      - DEBUG=1
      # setting.pyに記載されているSECRET_KEYを記入
      - SECRET_KEY=hoge
